### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [QiuFeng54321/muser#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.2.1.2. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary muser -w /tmp/ext muser==1.2.1.2
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting muser==1.2.1.2
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/2a9/74b4aef0af1ad/muser-1.2.1.2.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-kk7u61ln/muser/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-kk7u61ln/muser/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-kk7u61ln/muser/pip-egg-info
         cwd: /tmp/pip-wheel-kk7u61ln/muser/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-kk7u61ln/muser/setup.py", line 32, in <module>
        with open("../README.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: '../README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
I don't really understand this packaging style; I gave an attempt but I don't know if it includes the right source files for you.

**Comment by WilliamQiufeng** [comment]
> It appears that the manifest is missing at least one file necessary to build
> from the sdist for version 1.2.1.2. You're in good company, about 5% of other
> projects updated in the last year are also missing files.
> 
> ```
> + /tmp/venv/bin/pip3 wheel --no-binary muser -w /tmp/ext muser==1.2.1.2
> Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
> Collecting muser==1.2.1.2
>   Downloading http://10.10.0.139:9191/root/pypi/%2Bf/2a9/74b4aef0af1ad/muser-1.2.1.2.tar.gz (19 kB)
>     ERROR: Command errored out with exit status 1:
>      command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-kk7u61ln/muser/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-kk7u61ln/muser/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-kk7u61ln/muser/pip-egg-info
>          cwd: /tmp/pip-wheel-kk7u61ln/muser/
>     Complete output (5 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-wheel-kk7u61ln/muser/setup.py", line 32, in <module>
>         with open("../README.md", "r") as fh:
>     FileNotFoundError: [Errno 2] No such file or directory: '../README.md'
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ```

This is a problem I had had once tried to solve. However since it had been new concept to me I struggled and failed to fixed it so I just ended up recommending people just cloning the repository. 
I will try fixing it(probably in a few weeks because I am a student, I have got less time doing this and I haven't been working on this repo for months and would need reviewing) and I recommend using repo cloning while this bug still exists.
P.S.: I am working on unity version of this project because the framework I am using lacks functionality(Like window size limit, music playing, etc.), that is why I had stopped.
P.S.: There are some structral problems(as your comment said). I had tried to fix it too but I also encountered sth(I forgot:-(  ). Anyways I will try fixing them :D
